{% extends "setuptools.yaml" %}

{% block package -%}
package:
  name: {{data.get('name').lower().replace(' ', '_')}}-dev-mkl
  version: {{data.get('version').split('_')[0]}}
{%- endblock %}

{% block build -%}

build:
  string: py27_1p
  script:
    - base=`dirname $RECIPE_DIR`
    - base=`dirname $base`
    - cp -r $base .
    - cd `basename $base`
    - $PYTHON setup.py version
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt

  {% block entry_points -%}
  entry_points: {{data.get('entry_points', {}).get('console_scripts', [])+data.get('entry_points', {}).get('gui_scripts', [])}}
  {%- endblock %}
  
  features: 
    - mkl

  track_features:
    - mkl

  preserve_egg_dir: True

{%- endblock %}

{% block requirements -%}
requirements:
  build:
    - python
    - setuptools
    - jinja2
    {% for req in data.get('install_requires', []) -%}
    - {{req|lower}}
    {% endfor %}
    - accelerate
    - arachnid-build
    
  run:
    - python
    - setuptools
    {% for req in data.get('install_requires', []) -%}
    - {{req|lower}}
    {% endfor %}
    - pyside
    - arachnid-spider
    - accelerate

{%- endblock %}

{% block test -%}
test:
  imports: {{data.get('packages')+['arachnid.core.image.spi._spider_ctf', 'arachnid.core.image.spi._spider_filter', 'arachnid.core.image.spi._spider_interpolate', 'arachnid.core.image.spi._spider_reconstruct', 'arachnid.core.image.spi._spider_rotate', 'arachnid.core.learn.core._fastdot', 'arachnid.core.orient.core._healpix', 'arachnid.core.orient.core._transformations', 'arachnid.core.parallel.core._omp']}}
{%- endblock -%}

{% block about -%}
about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  summary: {{data.get('summary')}}
{%- endblock %}
